export let SEARCH_ENGINE_LIST = [{
    id: 1,
    label: '搜索引擎',
    children: [
        {id: 2, label: 'Google',},
        {id: 3, label: 'Yahoo',},
        {id: 4, label: 'Bing',},
        {id: 5, label: 'HotBot',},
        {id: 6, label: 'Ask',},
    ]
}];

export let COUNTRY_LIST = [{
    id: 1,
    label: '所有国家',
    children: [
        {
            id: 1111,
            label: '一带一路国家',
            children: [
                {id: 2, label: '新加坡',},
                {id: 3, label: '马来西亚',},
                {id: 4, label: '印度尼西亚',},
                {id: 5, label: '缅甸',},
                {id: 6, label: '泰国',},
                {id: 7, label: '老挝',},
                {id: 8, label: '柬埔寨',},
                {id: 9, label: '越南',},
                {id: 10, label: '文莱',},
                {id: 11, label: '伊朗',},
                {id: 12, label: '伊拉克',},
                {id: 13, label: '土耳其',},
                {id: 14, label: '叙利亚',},
                {id: 15, label: '约旦',},
                {id: 16, label: '黎巴嫩',},
                {id: 17, label: '以色列',},
                {id: 18, label: '巴勒斯坦',},
                {id: 19, label: '沙特阿拉伯',},
                {id: 20, label: '印度',},
                {id: 21, label: '巴基斯坦',},
                {id: 22, label: '孟加拉',},
                {id: 23, label: '阿富汗',},
                {id: 24, label: '斯里兰卡',},
                {id: 25, label: '马尔代夫',},
                {id: 26, label: '尼泊尔',},
                {id: 27, label: '哈萨克斯坦',},
                {id: 28, label: '乌兹别克斯坦',},
                {id: 29, label: '土库曼斯坦',},
                {id: 30, label: '俄罗斯',},
                {id: 31, label: '乌克兰',},
                {id: 32, label: '白俄罗斯',},
                {id: 33, label: '格鲁吉亚',},
                {id: 34, label: '阿塞拜疆',},
                {id: 35, label: '波兰',},
                {id: 36, label: '立陶宛',},
                {id: 37, label: '爱沙尼亚',},
                {id: 38, label: '摩尔多瓦',},
                {id: 39, label: '捷克',},
                {id: 40, label: '斯洛伐克',},
                {id: 41, label: '匈牙利',},
                {id: 42, label: '塞尔维亚',},
                {id: 43, label: '波黑',},
                {id: 44, label: '塞尔维亚',},
                {id: 45, label: '保加利亚',},
                {id: 46, label: '马其顿',},
            ]
        },
        {
            id: 47, label: '亚洲',
            children: [
                {id: 48, label: '中国香港',},
                {id: 49, label: '中国台湾',},
                {id: 50, label: '蒙古',},
                {id: 51, label: '韩国',},
                {id: 52, label: '日本',},
                {id: 53, label: '文莱达鲁萨兰国',},
                {id: 54, label: '菲律宾',},
                {id: 55, label: '东帝汶',},
                {id: 56, label: '哈萨克斯坦',},
                {id: 57, label: '吉尔吉斯斯坦',},
                {id: 58, label: '塔吉克斯坦',},
                {id: 59, label: '乌兹别克斯坦',},
                {id: 60, label: '土库曼斯坦',},
                {id: 61, label: '阿富汗',},
                {id: 62, label: '巴基斯坦',},
                {id: 63, label: '尼泊尔',},
                {id: 64, label: '印度',},
                {id: 65, label: '孟加拉国',},
                {id: 66, label: '斯里兰卡',},
                {id: 67, label: '马尔代夫',},
                {id: 68, label: '科威特',},
                {id: 69, label: '沙特阿拉伯',},
                {id: 70, label: '巴林',},
                {id: 71, label: '阿联酋',},
                {id: 72, label: '阿曼',},
                {id: 73, label: '约旦',},
                {id: 74, label: '以色列',},
                {id: 75, label: '黎巴嫩',},
                {id: 76, label: '土耳其',},
                {id: 77, label: '阿塞拜疆',},
                {id: 78, label: '亚美尼亚',},
            ]
        },
        {
            id: 79, label: '欧洲',
            children: [
                {id: 80, label: '冰岛',},
                {id: 81, label: '丹麦',},
                {id: 82, label: '挪威',},
                {id: 83, label: '瑞典',},
                {id: 84, label: '芬兰',},
                {id: 85, label: '爱沙尼亚',},
                {id: 86, label: '拉脱维亚',},
                {id: 87, label: '立陶宛',},
                {id: 88, label: '爱尔兰',},
                {id: 89, label: '英国',},
                {id: 90, label: '泽西',},
                {id: 91, label: '马恩',},
                {id: 92, label: '法国',},
                {id: 93, label: '荷兰',},
                {id: 94, label: '比利时',},
                {id: 95, label: '卢森堡',},
                {id: 96, label: '德国',},
                {id: 97, label: '奥地利',},
                {id: 98, label: '瑞士',},
                {id: 99, label: '列支郭士登',},
                {id: 100, label: '葡萄牙',},
                {id: 101, label: '西班牙',},
                {id: 102, label: '直布罗陀',},
                {id: 103, label: '安道尔',},
                {id: 104, label: '意大利',},
                {id: 105, label: '马耳他',},
                {id: 106, label: '圣马力诺',},
                {id: 107, label: '希腊',},
                {id: 108, label: '俄罗斯',},
                {id: 109, label: '白俄罗斯',},
                {id: 110, label: '乌克兰',},
                {id: 111, label: '阿根廷',},
                {id: 112, label: '捷克',},
                {id: 113, label: '斯洛伐克',},
                {id: 114, label: '匈牙利',},
                {id: 115, label: '斯洛文尼亚',},
                {id: 116, label: '克罗地亚',},
                {id: 117, label: '黑山',},
                {id: 118, label: '塞尔维亚',},
                {id: 119, label: '马其顿',},
                {id: 120, label: '保加利亚',},
                {id: 121, label: '罗马尼亚',},
                {id: 122, label: '摩尔多瓦',},
            ]
        },
        {
            id: 123, label: '南美洲',
            children: [
                {id: 124, label: '多米尼加',},
                {id: 125, label: '特立尼达和多巴哥',},
                {id: 126, label: '哥伦比亚',},
                {id: 127, label: '厄瓜多尔',},
                {id: 128, label: '圭亚那',},
                {id: 129, label: '西班牙',},
                {id: 130, label: '秘鲁',},
                {id: 131, label: '玻利维亚',},
                {id: 132, label: '巴拉圭',},
                {id: 133, label: '智利',},
                {id: 134, label: '危地马拉',},
                {id: 135, label: '伯利兹',},
                {id: 136, label: '萨尔瓦多',},
                {id: 137, label: '洪都拉斯',},
                {id: 138, label: '尼加拉瓜',},
                {id: 139, label: '哥斯达黎加',},
                {id: 140, label: '巴拿马',},
                {id: 141, label: '巴哈马',},
                {id: 142, label: '古巴',},
                {id: 143, label: '牙买加',},
                {id: 144, label: '海地',},
            ]
        },
        {
            id: 145, label: '北美洲',
            children: [
                {id: 146, label: '格陵兰',},
                {id: 147, label: '加拿大',},
                {id: 148, label: '美国',},
                {id: 149, label: '墨西哥',},
            ]
        },
        {
            id: 150, label: '大洋洲',
            children: [
                {id: 151, label: '澳大利亚',},
                {id: 152, label: '诺福克岛',},
                {id: 153, label: '新西兰',},
                {id: 154, label: '所罗门群岛',},
                {id: 155, label: '斐济',},
                {id: 156, label: '密克罗尼西亚',},
                {id: 157, label: '瑙鲁',},
                {id: 158, label: '托克劳',},
                {id: 159, label: '萨摩亚',},
                {id: 160, label: '东萨摩亚',},
                {id: 161, label: '汤加',},
                {id: 162, label: '纽埃',},
                {id: 163, label: '库克群岛',},
            ]
        },
        {
            id: 164, label: '非洲',
            children: [
                {id: 165, label: '莱索托',},
                {id: 166, label: '埃及',},
                {id: 167, label: '利比亚',},
                {id: 168, label: '阿尔及利亚',},
                {id: 169, label: '摩洛哥',},
                {id: 170, label: '塞内加尔',},
                {id: 171, label: '冈比亚',},
                {id: 172, label: '马里',},
                {id: 173, label: '布基纳法索',},
                {id: 174, label: '塞拉利昂',},
                {id: 175, label: '科特迪瓦',},
                {id: 176, label: '加纳',},
                {id: 177, label: '多哥',},
                {id: 178, label: '贝宁',},
                {id: 179, label: '尼日尔',},
                {id: 180, label: '尼日利亚',},
                {id: 181, label: '圣赫勒拿',},
                {id: 182, label: '喀麦隆',},
                {id: 183, label: '乍得',},
                {id: 184, label: '中非',},
                {id: 185, label: '加蓬',},
                {id: 186, label: '刚果【布】',},
                {id: 187, label: '刚果【金】',},
                {id: 188, label: '安哥拉',},
                {id: 189, label: '埃塞俄比亚',},
                {id: 190, label: '吉布提',},
                {id: 191, label: '肯尼亚',},
                {id: 192, label: '乌干达',},
                {id: 193, label: '坦桑尼亚',},
                {id: 194, label: '卢旺达',},
                {id: 195, label: '布隆迪',},
                {id: 196, label: '马拉维',},
                {id: 197, label: '莫桑比克',},
                {id: 198, label: '马达加斯加',},
                {id: 199, label: '塞舌尔',},
                {id: 200, label: '毛里求斯',},
                {id: 201, label: '赞比亚',},
                {id: 202, label: '津巴布韦',},
                {id: 203, label: '博茨瓦纳',},
                {id: 204, label: '纳米比亚',},
                {id: 205, label: '南非',},
            ]
        }
    ]
}];
